name: Cypress Test

on:
  push:
    branches:
      - main

  workflow_dispatch:
     inputs:
      COMPANY_NAME:
        description: 'Name of the company'     
        required: true
      GAME:
        description: 'Game name'  
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_COMPANY_NAME: ${{ github.event.inputs.COMPANY_NAME }}
          CYPRESS_GAME: ${{ github.event.inputs.GAME }}
        with:
          command: npx cypress run
          record: false
          browser: electron
          

          
