name: Cypress Test

on:
  push:
    branches:
      - main

  workflow_dispatch: # Allow manual triggering of workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with recording
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_COMPANY_NAME: ${{ github.event.inputs.COMPANY_NAME }}
          CYPRESS_GAME: ${{ github.event.inputs.GAME }}
        with:
          command: npx cypress run
          record: false
          browser: electron
          

          
